### ISSUE TITLE
History button

### ISSUE THREAD

**Issue by samtay** [BlueAcornInc/devops-hipchat-deploybot#2]
History button doesn't do anything right now. It should either open up a dialog or output the information via hipchat card.

**Comment by briceburg** [comment]
There's two ways to support history now --

  * via the _original_ api call to `<api>/history/:SKEL?`
  * or via the frontend application call `/history/:SKEL`, e.g. http://deploybot.badevops.com/history/RDS

The API call requires parsing JSON in the hipchat-connect code to render a result, where-as the application call allows us to either:
  * embed the result for the frontend call in an iframe
  * open a new window in the user's browser (my choice).

so we have a simple to implement solution with this change.

**Comment by SamTay** [comment]
Cool. Thanks @briceburg. Also FYI you can include <a> tags within the sidebar content and these will open up webpages within the sidebar (like an iframe). Hopefully including a target="_blank" or whatever will open up the browser.
